schedule: "every month"
search: False
requirements:
  - requirements/default.txt:
      update: all
      pin: true
  - requirements/constraints.txt:
      update: all
      pin: true
  - requirements/all.txt:
      update: security
  - requirements/build.txt:
      update: security
