dist: trusty

cache:
  pip: true
  directories:
    - datamaps/
    - libmaxminddb/
    - pngquant/

addons:
  apt:
    packages:
      - gfortran
      - libatlas-base-dev
      - libatlas-dev
      - libgmp-dev
      - liblapack-dev
      - libmpfr-dev
      - libspatialindex-dev

language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - jwhitlock@mozilla.com

script:
    - pip install -U pip
    - travis_wait make build
    - make release_compile
    # https://github.com/travis-ci/travis-ci/issues/7940
    - export BOTO_CONFIG=/dev/null
    - make test
    - make docs

services:
  - mysql
  - redis-server
