# new container based environment
sudo: false

cache:
  pip: true
  directories:
    - libmaxminddb/

language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"

notifications:
  email:
    - hschlichting@mozilla.com

script:
    - pip install -U pip
    - make build
    - make release_compile
    - make test
    - make docs

after_success:
    - make coveralls

# mysql is started automatically
services:
  - redis-server
