mysql:
    build: docker/mysql
    container_name: mozilla-ichnaea-mysql
    ports:
        - "33306:3306"

redis:
    build: docker/redis
    container_name: mozilla-ichnaea-redis
    ports:
        - "36379:6379"
