mysql:
  container_name: ichnaea_mysql
  expose:
    - "3306"
  image: mozilla-ichnaea/mysql:latest
  ports:
    - "3306"

redis:
  container_name: ichnaea_redis
  expose:
    - "6379"
  image: mozilla-ichnaea/redis:latest
  ports:
    - "6379"
