[UdpInput]
address = "0.0.0.0:5565"
parser_type = "message.proto"
decoder = "ProtobufDecoder"

[StatsdInput]
address = "0.0.0.0:8125"
stat_accum_name = "StatAccumulator"

[StatAccumulator]
type="StatAccumInput"
emit_in_payload = true
# For local development and verification ticker_interval is set low.
# In production you like want to stick with 60 seconds instead.
ticker_interval = 5

[CarbonOutput]
message_matcher = "Type == 'heka.statmetric'"

# You can comment this block out if you don't want hekad to spew log
# messages to stdout
[LogOutput]
message_matcher = "TRUE"
payload_only = false

[SentryOutput]
max_udp_sockets = 100
max_sentry_bytes = 100000
message_matcher = "Type == 'sentry'"
